In [1]:
import numpy as np
import pandas as pd

In [2]:
books = pd.read_csv("Books.csv")
users =pd.read_csv("Users.csv")
ratings = pd.read_csv("Ratings.csv")

C:\Users\RJ\AppData\Local\Temp\ipykernel_21896\2332716364.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv("Books.csv")

In [3]:
books.sample(6)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
19052,0689846258,"Jennifer, Hecate, MacBeth, William McKinley an...",E.L. Konigsburg,2001,Aladdin,http://images.amazon.com/images/P/0689846258.0...,http://images.amazon.com/images/P/0689846258.0...,http://images.amazon.com/images/P/0689846258.0...
248181,0679910565,Aliens for Lunch,STEPHANIE SPINNER,1991,Random House Books for Young Readers,http://images.amazon.com/images/P/0679910565.0...,http://images.amazon.com/images/P/0679910565.0...,http://images.amazon.com/images/P/0679910565.0...
60293,0151005575,"Looking for Spinoza: Joy, Sorrow, and the Feel...",Antonio Damasio,2003,Harcourt,http://images.amazon.com/images/P/0151005575.0...,http://images.amazon.com/images/P/0151005575.0...,http://images.amazon.com/images/P/0151005575.0...
198990,1550371444,Baseball Bats for Christmas,Michael Kusugak,1993,Annick Press,http://images.amazon.com/images/P/1550371444.0...,http://images.amazon.com/images/P/1550371444.0...,http://images.amazon.com/images/P/1550371444.0...
265283,0671794779,The Nancy Drew Files Case #85: Sea of Suspicion,Carolyn Keene,1993,Simon Pulse,http://images.amazon.com/images/P/0671794779.0...,http://images.amazon.com/images/P/0671794779.0...,http://images.amazon.com/images/P/0671794779.0...
221908,0385058144,Six war years 1939-1945: Memories of Canadians...,Barry Broadfoot,1974,Doubleday,http://images.amazon.com/images/P/0385058144.0...,http://images.amazon.com/images/P/0385058144.0...,http://images.amazon.com/images/P/0385058144.0...

In [4]:
users.sample(6)

        User-ID                   Location   Age
144469   144470  bayville, new jersey, usa  28.0
51638     51639      mexico, missouri, usa   NaN
264306   264307   columbus, wisconsin, usa   NaN
11290     11291    napoli, campania, italy  37.0
84981     84982         spring, texas, usa   NaN
228669   228670          farley, iowa, usa   NaN

In [5]:
ratings.sample(6)

         User-ID        ISBN  Book-Rating
890288    214786  0425136981            0
790756    190925  0671028375            0
245889     56399  0738700738           10
662900    160819  039592720X            0
1043622   249862  0553574957            0
356192     85769  9727110819            4

In [6]:
print("books :-",books.shape)
print("users :-",users.shape)
print("ratings :_",ratings.shape)

books :- (271360, 8)
users :- (278858, 3)
ratings :_ (1149780, 3)

In [7]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [8]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [9]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [10]:
books.duplicated().sum()

0

In [11]:
users.duplicated().sum()

0

# Popularity based reccomendation system

In [12]:
ratings_with_name = ratings.merge(books,on="ISBN")

In [13]:
ratings_with_name.shape

(1031136, 10)

In [14]:
ratings_with_name.sample(6)

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
715394,68257,0385336195,0,The Best Revenge,Stephen White,2003,Delacorte Press,http://images.amazon.com/images/P/0385336195.0...,http://images.amazon.com/images/P/0385336195.0...,http://images.amazon.com/images/P/0385336195.0...
539280,52917,0688149553,6,Mash: A Novel About Three Army Doctors,Richard Hooker,1997,Perennial,http://images.amazon.com/images/P/0688149553.0...,http://images.amazon.com/images/P/0688149553.0...,http://images.amazon.com/images/P/0688149553.0...
921851,140863,3770149904,4,Aus fÃ?Â¼r den Milchmann.,Charlotte MacLeod,2000,DUMONT Literatur und Kunst Verlag,http://images.amazon.com/images/P/3770149904.0...,http://images.amazon.com/images/P/3770149904.0...,http://images.amazon.com/images/P/3770149904.0...
965618,235842,0030624703,0,Indians of Mexico a Book to Begin on,M. C. Farquhar,1967,Holt Rinehart &amp; Winston,http://images.amazon.com/images/P/0030624703.0...,http://images.amazon.com/images/P/0030624703.0...,http://images.amazon.com/images/P/0030624703.0...
454624,183347,0312969198,7,A Cold Day in Paradise (Alex McKnight Mysterie...,Steve Hamilton,2000,St. Martin's Minotaur,http://images.amazon.com/images/P/0312969198.0...,http://images.amazon.com/images/P/0312969198.0...,http://images.amazon.com/images/P/0312969198.0...
355866,185233,0425179885,0,The Devil's Code,John Sandford,2004,Berkley Publishing Group,http://images.amazon.com/images/P/0425179885.0...,http://images.amazon.com/images/P/0425179885.0...,http://images.amazon.com/images/P/0425179885.0...

In [15]:
ratings_with_name["ISBN"].duplicated().sum()

760985

In [16]:
ratings_with_name.isnull().sum()

User-ID                0
ISBN                   0
Book-Rating            0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            4
dtype: int64

In [17]:
ratings_with_name.dtypes

User-ID                 int64
ISBN                   object
Book-Rating             int64
Book-Title             object
Book-Author            object
Year-Of-Publication    object
Publisher              object
Image-URL-S            object
Image-URL-M            object
Image-URL-L            object
dtype: object

### no. of rating of a book

In [18]:
num_ratings_df = ratings_with_name.groupby("Book-Title").count()["Book-Rating"].reset_index()
num_ratings_df.rename(columns={"Book-Rating":"num_ratings"},inplace=True)
num_ratings_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [19]:
avg_ratings_df = ratings_with_name.groupby("Book-Title")["Book-Rating"].mean().reset_index()
avg_ratings_df.rename(columns={"Book-Rating":"avg_ratings"},inplace=True)
avg_ratings_df

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [20]:
popular_df = avg_ratings_df.merge(num_ratings_df,on="Book-Title")
popular_df

,Book-Title,avg_ratings,num_ratings
0,A Light in the Storm: The Civil War Diary of ...,2.250000,4
1,Always Have Popsicles,0.000000,1
2,Apple Magic (The Collector's series),0.000000,1
3,"Ask Lily (Young Women of Faith: Lily Series, ...",8.000000,1
4,Beyond IBM: Leadership Marketing and Finance ...,0.000000,1
...,...,...,...
241066,Ã?Â?lpiraten.,0.000000,2
241067,Ã?Â?rger mit Produkt X. Roman.,5.250000,4
241068,Ã?Â?sterlich leben.,7.000000,1
241069,Ã?Â?stlich der Berge.,2.666667,3
241070,Ã?Â?thique en toc,4.000000,2

In [21]:
popular_df = popular_df[popular_df["num_ratings"]>=250].sort_values("avg_ratings",ascending= False).head(50)
popular_df

,Book-Title,avg_ratings,num_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),5.852804,428
80422,Harry Potter and the Goblet of Fire (Book 4),5.824289,387
80441,Harry Potter and the Sorcerer's Stone (Book 1),5.737410,278
80426,Harry Potter and the Order of the Phoenix (Boo...,5.501441,347
80414,Harry Potter and the Chamber of Secrets (Book 2),5.183453,556
191612,The Hobbit : The Enchanting Prelude to The Lor...,5.007117,281
187377,The Fellowship of the Ring (The Lord of the Ri...,4.948370,368
80445,Harry Potter and the Sorcerer's Stone (Harry P...,4.895652,575
211384,"The Two Towers (The Lord of the Rings, Part 2)",4.880769,260
219741,To Kill a Mockingbird,4.700000,510
183573,The Da Vinci Code,4.642539,898
187880,The Five People You Meet in Heaven,4.551163,430
180556,The Catcher in the Rye,4.545657,449
196326,The Lovely Bones: A Novel,4.468726,1295
764,1984,4.454225,284
144165,Prodigal Summer: A Novel,4.450593,253
128670,Neverwhere,4.449057,265
206502,The Secret Life of Bees,4.447028,774
168719,Stupid White Men ...and Other Sorry Excuses fo...,4.356890,283
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",4.354970,493
204387,The Red Tent (Bestselling Backlist),4.334716,723
191589,The Hitchhiker's Guide to the Galaxy,4.328358,268
129379,Nickel and Dimed: On (Not) Getting By in America,4.289552,335
93381,Into the Wild,4.273810,252
63867,Fahrenheit 451,4.264059,409
74750,Girl with a Pearl Earring,4.218631,526
136145,Outlander,4.173145,283
233370,Where the Heart Is (Oprah's Book Club (Paperba...,4.105983,585
156102,Seabiscuit: An American Legend,4.098182,275
107962,Life of Pi,4.088855,664
176845,The Bean Trees,4.087404,389
2281,"A Child Called \It\"": One Child's Courage to S...",4.086792,265
8434,ANGELA'S ASHES,4.075269,279
76343,Good in Bed,4.055102,490
64931,Fast Food Nation: The Dark Side of the All-Ame...,4.037383,321
12700,American Gods,4.006623,302
161645,Skipping Christmas,4.006211,322
105777,Left Behind: A Novel of the Earth's Last Days ...,4.003145,318
189551,"The Golden Compass (His Dark Materials, Book 1)",4.000000,336
181679,The Color Purple,3.964968,314
160336,Silence of the Lambs,3.960938,256
8752,About a Boy,3.900763,262
158138,Seven Up (A Stephanie Plum Novel),3.888489,278
175097,The Alchemist: A Fable About Following Your Dream,3.875940,266
80069,Hard Eight : A Stephanie Plum Novel (A Stephan...,3.825279,269
170101,Suzanne's Diary for Nicholas,3.820569,457
111073,Lord of the Flies,3.818533,259
5664,A Prayer for Owen Meany,3.796610,413
212070,"The Vampire Lestat (Vampire Chronicles, Book II)",3.777409,301
233851,White Oleander : A Novel (Oprah's Book Club),3.772472,356

In [22]:
popular_df=popular_df.merge(books,on="Book-Title").drop_duplicates("Book-Title")[["Book-Title","Book-Author","Image-URL-M","num_ratings","avg_ratings"]]

In [23]:
popular_df

,Book-Title,Book-Author,Image-URL-M,num_ratings,avg_ratings
0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,http://images.amazon.com/images/P/0439136350.0...,428,5.852804
3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,http://images.amazon.com/images/P/0439139597.0...,387,5.824289
5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,http://images.amazon.com/images/P/0590353403.0...,278,5.737410
9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,http://images.amazon.com/images/P/043935806X.0...,347,5.501441
13,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,http://images.amazon.com/images/P/0439064872.0...,556,5.183453
16,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339681.0...,281,5.007117
17,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339703.0...,368,4.948370
26,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,http://images.amazon.com/images/P/059035342X.0...,575,4.895652
28,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,http://images.amazon.com/images/P/0345339711.0...,260,4.880769
39,To Kill a Mockingbird,Harper Lee,http://images.amazon.com/images/P/0446310786.0...,510,4.700000
47,The Da Vinci Code,Dan Brown,http://images.amazon.com/images/P/0385504209.0...,898,4.642539
53,The Five People You Meet in Heaven,Mitch Albom,http://images.amazon.com/images/P/0786868716.0...,430,4.551163
55,The Catcher in the Rye,J.D. Salinger,http://images.amazon.com/images/P/0316769487.0...,449,4.545657
62,The Lovely Bones: A Novel,Alice Sebold,http://images.amazon.com/images/P/0316666343.0...,1295,4.468726
63,1984,George Orwell,http://images.amazon.com/images/P/0451524934.0...,284,4.454225
72,Prodigal Summer: A Novel,Barbara Kingsolver,http://images.amazon.com/images/P/0060959037.0...,253,4.450593
73,Neverwhere,Neil Gaiman,http://images.amazon.com/images/P/0380789019.0...,265,4.449057
78,The Secret Life of Bees,Sue Monk Kidd,http://images.amazon.com/images/P/0142001740.0...,774,4.447028
84,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,http://images.amazon.com/images/P/0060392452.0...,283,4.356890
85,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,http://images.amazon.com/images/P/0385484518.0...,493,4.354970
88,The Red Tent (Bestselling Backlist),Anita Diamant,http://images.amazon.com/images/P/0312195516.0...,723,4.334716
89,The Hitchhiker's Guide to the Galaxy,Douglas Adams,http://images.amazon.com/images/P/0671461494.0...,268,4.328358
98,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,http://images.amazon.com/images/P/0805063897.0...,335,4.289552
100,Into the Wild,Jon Krakauer,http://images.amazon.com/images/P/0385486804.0...,252,4.273810
103,Fahrenheit 451,Ray Bradbury,http://images.amazon.com/images/P/3257208626.0...,409,4.264059
116,Girl with a Pearl Earring,Tracy Chevalier,http://images.amazon.com/images/P/0452282152.0...,526,4.218631
117,Outlander,DIANA GABALDON,http://images.amazon.com/images/P/0440222915.0...,283,4.173145
123,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,http://images.amazon.com/images/P/0446672211.0...,585,4.105983
124,Seabiscuit: An American Legend,LAURA HILLENBRAND,http://images.amazon.com/images/P/0449005615.0...,275,4.098182
126,Life of Pi,Yann Martel,http://images.amazon.com/images/P/0151008116.0...,664,4.088855
130,The Bean Trees,Barbara Kingsolver,http://images.amazon.com/images/P/0060915544.0...,389,4.087404
133,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,http://images.amazon.com/images/P/1558743669.0...,265,4.086792
135,ANGELA'S ASHES,Frank McCourt,http://images.amazon.com/images/P/0684874350.0...,279,4.075269
137,Good in Bed,Jennifer Weiner,http://images.amazon.com/images/P/0743418174.0...,490,4.055102
139,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,http://images.amazon.com/images/P/0060938455.0...,321,4.037383
140,American Gods,Neil Gaiman,http://images.amazon.com/images/P/0380789035.0...,302,4.006623
141,Skipping Christmas,JOHN GRISHAM,http://images.amazon.com/images/P/0385505833.0...,322,4.006211
147,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,http://images.amazon.com/images/P/0842329129.0...,318,4.003145
149,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,http://images.amazon.com/images/P/037582345X.0...,336,4.000000
157,The Color Purple,Alice Walker,http://images.amazon.com/images/P/0671617028.0...,314,3.964968
163,Silence of the Lambs,Thomas Harris,http://images.amazon.com/images/P/0312924585.0...,256,3.960938
166,About a Boy,Nick Hornby,http://images.amazon.com/images/P/1573227331.0...,262,3.900763
173,Seven Up (A Stephanie Plum Novel),Janet Evanovich,http://images.amazon.com/images/P/0312265840.0...,278,3.888489
175,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,http://images.amazon.com/images/P/0062502174.0...,266,3.875940
177,Hard Eight : A Stephanie Plum Novel (A Stephan...,Janet Evanovich,http://images.amazon.com/images/P/0312983867.0...,269,3.825279
182,Suzanne's Diary for Nicholas,James Patterson,http://images.amazon.com/images/P/0316969443.0...,457,3.820569
186,Lord of the Flies,William Gerald Golding,http://images.amazon.com/images/P/0399501487.0...,259,3.818533
192,A Prayer for Owen Meany,John Irving,http://images.amazon.com/images/P/0345361792.0...,413,3.796610
194,"The Vampire Lestat (Vampire Chronicles, Book II)",ANNE RICE,http://images.amazon.com/images/P/0345313860.0...,301,3.777409
195,White Oleander : A Novel (Oprah's Book Club),Janet Fitch,http://images.amazon.com/images/P/0316284955.0...,356,3.772472

# Collaborative filter based recommender system

In [24]:
ratings_with_name

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [25]:
x = ratings_with_name.groupby("User-ID").count()["Book-Rating"] > 200
padhe_likhe_users = x[x].index

In [26]:
filtered_rating = ratings_with_name[ratings_with_name["User-ID"].isin(padhe_likhe_users)]

In [27]:
y = filtered_rating.groupby("Book-Title").count()["Book-Rating"] >=50
famous_books = y[y].index

In [28]:
final_ratings = filtered_rating[filtered_rating["Book-Title"].isin(famous_books)]

In [29]:
final_ratings

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
63,278418,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
65,3363,0446520802,0,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
66,7158,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
69,11676,0446520802,10,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
74,23768,0446520802,6,The Notebook,Nicholas Sparks,1996,Warner Books,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...,http://images.amazon.com/images/P/0446520802.0...
...,...,...,...,...,...,...,...,...,...,...
1026724,266865,0531001725,10,The Catcher in the Rye,Jerome David Salinger,1973,Scholastic Library Pub,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...,http://images.amazon.com/images/P/0531001725.0...
1027923,269566,0670809381,0,Echoes,Maeve Binchy,1986,Penguin USA,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...,http://images.amazon.com/images/P/0670809381.0...
1028777,271284,0440910927,0,The Rainmaker,John Grisham,1995,Island,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...,http://images.amazon.com/images/P/0440910927.0...
1029070,271705,B0001PIOX4,0,Fahrenheit 451,Ray Bradbury,1993,Simon &amp; Schuster,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...,http://images.amazon.com/images/P/B0001PIOX4.0...
1030868,275970,1586210661,9,Me Talk Pretty One Day,David Sedaris,2001,Time Warner Audio Major,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...,http://images.amazon.com/images/P/1586210661.0...

In [30]:
pt = final_ratings.pivot_table(index="Book-Title",columns="User-ID",values="Book-Rating")
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,10.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,NaN,NaN,NaN,7.0,NaN,NaN,NaN,NaN,NaN,0.0,...,NaN,9.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
You Belong To Me,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,8.0,NaN,NaN,NaN,NaN,NaN

In [31]:
pt.fillna(0,inplace=True)
pt

User-ID,254,2276,2766,2977,3363,4017,4385,6251,6323,6543,...,271705,273979,274004,274061,274301,274308,275970,277427,277639,278418
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Year of Wonders,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
You Belong To Me,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zen and the Art of Motorcycle Maintenance: An Inquiry into Values,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,8.0,0.0,0.0,0.0,0.0,0.0

In [32]:
from sklearn.metrics.pairwise import cosine_similarity
similarity_score = cosine_similarity(pt)

In [33]:
similarity_score.shape

(706, 706)

In [42]:
def recommend(book_name):
    #fetching index
    index = np.where(pt.index == book_name)[0][0]
    similar_items  = sorted(list(enumerate(similarity_score[index])),key= lambda x:x[1],reverse =True)[1:6]

    data = []
    for i in similar_items:
        item =[]
        temp_df = books[books["Book-Title"] == pt.index[i[0]]]
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Title"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Book-Author"].values))
        item.extend(list(temp_df.drop_duplicates("Book-Title")["Image-URL-M"].values))
        data.append(item)
    return data

In [43]:
recommend("The Notebook")

[['A Walk to Remember',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446608955.01.MZZZZZZZ.jpg'],
 ['The Rescue',
  'Nicholas Sparks',
  'http://images.amazon.com/images/P/0446610399.01.MZZZZZZZ.jpg'],
 ['One Door Away from Heaven',
  'Dean R. Koontz',
  'http://images.amazon.com/images/P/0553582755.01.MZZZZZZZ.jpg'],
 ['Toxin',
  'Robin Cook',
  'http://images.amazon.com/images/P/0425166619.01.MZZZZZZZ.jpg'],
 ['The Five People You Meet in Heaven',
  'Mitch Albom',
  'http://images.amazon.com/images/P/0786868716.01.MZZZZZZZ.jpg']]

In [36]:
import pickle
pickle.dump(popular_df,open("popular.pkl","wb"))

In [45]:
pickle.dump(pt,open("pt.pkl","wb"))
pickle.dump(books,open("books.pkl","wb"))
pickle.dump(similarity_score,open("similarity_scores.pkl","wb"))